# -*- coding: utf-8 -*-
"""IntrusionDetectionSystem .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QtLqWNKLJ7wmlzkezc2bSlQqTvYgCv7
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical

data = pd.read_csv("/content/drive/MyDrive/2022.06.13.csv")

file_path = '/content/drive/MyDrive/2022.06.13.csv'
df = pd.read_csv(file_path)

df.fillna(0, inplace=True)
df.columns = df.columns.str.strip()

label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['label'])


# Step 4: Feature selection (dropping non-numeric or irrelevant columns)
columns_to_drop = ['dest_ip', 'src_ip', 'time_start', 'time_end']  # Adjust as necessary
df = df.drop(columns=columns_to_drop, axis=1)

# Step 5: Split data into features (X) and target (y)
X = df.drop('label', axis=1)
y = df['label']

# Step 6: Scale numerical features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 7: Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

print("Preprocessing complete. Ready for model training!")

data.info()
data.describe()

data.dropna(inplace=True)

data = data.replace([np.inf, -np.inf], np.nan).dropna()

Target= 'label'
X = data.loc[:, data.columns != Target]
y = data.loc[:,Target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['label'])
X = df.drop(columns=['label'])  # Features
y = df['label']
non_numeric_columns = X.select_dtypes(include=['object']).columns
for col in non_numeric_columns:
    X[col] = label_encoder.fit_transform(X[col])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

# Step 8: Convert to NumPy arrays and reshape for models requiring 3D input
X_train = np.array(X_train).reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = np.array(X_test).reshape(X_test.shape[0], X_test.shape[1], 1)

print(X_train)

print(X_test)

"""CNN"""

model = keras.Sequential([
    layers.Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train.shape[1], 1)),
    layers.MaxPooling1D(pool_size=2),
    layers.Conv1D(128, kernel_size=3, activation='relu'),
    layers.MaxPooling1D(pool_size=2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(np.unique(y)), activation='softmax')  # Output layer for multi-class classification
])

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=5, batch_size=32, validation_split=0.2)

y_pred = np.argmax(model.predict(X_test), axis=-1)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))


plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()


plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

plt.show()

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.3f}')

recall = recall_score(y_test, y_pred, average='weighted')
print(f'Recall: {recall:.3f}')

f1 = f1_score(y_test, y_pred, average='weighted')
print(f'F1-Score: {f1:.3f}')

conf_matrix = confusion_matrix(y_test, y_pred)


print("Confusion Matrix:\n", conf_matrix)


plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=np.unique(y), yticklabels=np.unique(y))
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

print("\nClassification Report:\n", classification_report(y_test, y_pred))

import plotly.express as px

subject = data['label'].value_counts().reset_index(name='count')
subject['percentage'] = (subject['count'] / subject['count'].sum()) * 100
fig = px.bar(subject, x='label', y='count', text='percentage', title='Defects by Priority', template='ggplot2')
fig.update_traces(texttemplate='%{text:.0f}%')
fig.show()

def performance_graph(history):
    history_df = pd.DataFrame(history.history)
    fig, axs = plt.subplots(1, 2, figsize=(15, 4))
    history_df.loc[2:, ['loss', 'val_loss']].plot(ax=axs[0])
    history_df.loc[2:, ['accuracy', 'val_accuracy']].plot(ax=axs[1])

    print(("Best Validation Loss: {:0.4f}" +\
          "\nBest Validation accuracy: {:0.4f}")\
          .format(history_df['val_loss'].min(),
                  history_df['val_accuracy'].max()))
performance_graph(history)

"""LSTM model"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau


X = data.drop('label', axis=1)
y = data['label']


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


y_one_hot = to_categorical(y_encoded)


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_reshaped = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))


X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_one_hot, test_size=0.2, random_state=42)


model = Sequential()


model.add(LSTM(units=128, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.3))
model.add(BatchNormalization())


model.add(LSTM(units=64, return_sequences=False))
model.add(Dropout(0.3))
model.add(BatchNormalization())

model.add(Dense(units=y_one_hot.shape[1], activation='softmax'))


optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


model.summary()


early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.0001)


history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=64,
    validation_data=(X_test, y_test),
    callbacks=[early_stopping, reduce_lr]
)


y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)


print("Classification Report:")
print(classification_report(y_test_classes, y_pred_classes))
print(f"Test Accuracy: {accuracy_score(y_test_classes, y_pred_classes):.4f}")


model.save('lstm_nids_model_enhanced.h5')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, roc_curve, auc, RocCurveDisplay
from sklearn.preprocessing import label_binarize

# Evaluate the model
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

# Confusion Matrix
def plot_confusion_matrix(y_true, y_pred, classes, title='Confusion Matrix', cmap=plt.cm.Blues):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap=cmap, xticklabels=classes, yticklabels=classes)
    plt.title(title)
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

# Plot Confusion Matrix
class_names = label_encoder.classes_
plot_confusion_matrix(y_test_classes, y_pred_classes, classes=class_names)

"""GAN MODEL"""



import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import time
from torch.utils.data import DataLoader, TensorDataset


class Generator(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim),
            nn.Tanh()
        )

    def forward(self, z):
        return self.model(z)


class Discriminator(nn.Module):
    def __init__(self, input_dim):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)

def prepare_dataloader(X_train):
    X_tensor = torch.tensor(X_train, dtype=torch.float32)
    dataset = TensorDataset(X_tensor)
    return DataLoader(dataset, batch_size=64, shuffle=True), X_train.shape[1]


def train_gan(generator, discriminator, data_loader, num_epochs=50, lr=0.0001, latent_dim=20):
    loss_fn = nn.BCELoss()
    optimizer_G = optim.Adam(generator.parameters(), lr=lr)
    optimizer_D = optim.Adam(discriminator.parameters(), lr=lr)

    for epoch in range(num_epochs):
        start_time = time.time()
        batch_times = []

        for batch_idx, (real_data,) in enumerate(data_loader):
            batch_start_time = time.time()
            batch_size = real_data.size(0)

            real_labels = torch.full((batch_size, 1), 0.9, dtype=torch.float32)
            fake_labels = torch.full((batch_size, 1), 0.1, dtype=torch.float32)


            optimizer_D.zero_grad()
            real_output = discriminator(real_data)
            loss_real = loss_fn(real_output, real_labels)

            z = torch.randn(batch_size, latent_dim, dtype=torch.float32)
            fake_data = generator(z)
            fake_output = discriminator(fake_data.detach())
            loss_fake = loss_fn(fake_output, fake_labels)

            loss_D = loss_real + loss_fake
            loss_D.backward()
            optimizer_D.step()


            optimizer_G.zero_grad()
            fake_output = discriminator(fake_data)
            loss_G = loss_fn(fake_output, torch.ones(batch_size, 1, dtype=torch.float32))
            loss_G.backward()
            optimizer_G.step()

            batch_time = time.time() - batch_start_time
            batch_times.append(batch_time)
            avg_batch_time = sum(batch_times) / len(batch_times)
            batches_left = len(data_loader) - (batch_idx + 1)
            estimated_time_left = avg_batch_time * batches_left

            print(f"Batch [{batch_idx+1}/{len(data_loader)}], Estimated Time Left: {estimated_time_left:.2f} sec", end="\r")

        epoch_time = time.time() - start_time
        print(f"\nEpoch [{epoch}/{num_epochs}], Loss D: {loss_D.item():.4f}, Loss G: {loss_G.item():.4f}, Time: {epoch_time:.2f} sec")


def main():
    latent_dim = 20

    X_train_fixed = X_train.reshape(X_train.shape[0], -1)
    data_loader, input_dim = prepare_dataloader(X_train_fixed)

    generator = Generator(latent_dim, input_dim)
    discriminator = Discriminator(input_dim)

    train_gan(generator, discriminator, data_loader)

    return generator, discriminator


if __name__ == "__main__":
    generator, discriminator = main()

from sklearn.metrics import classification_report, accuracy_score

# 1. Prepare test data
X_test_flat = X_test.reshape(X_test.shape[0], -1)  # Flatten if it's 3D
X_test_tensor = torch.tensor(X_test_flat, dtype=torch.float32)

# 2. Make predictions using the discriminator
discriminator.eval()
with torch.no_grad():
    y_pred_scores = discriminator(X_test_tensor).numpy().flatten()
    y_pred_classes = (y_pred_scores > 0.5).astype(int)

# 3. Prepare true labels
# If your labels are one-hot encoded or categorical, convert them to binary
y_true = np.argmax(y_test, axis=1) if y_test.ndim == 2 else y_test
# Map all attack types to 1, and normal to 0
# Assuming label 0 = normal, others = attack
y_true_binary = np.where(y_true == 0, 0, 1)

# 4. Evaluate
print("\nClassification Report (Discriminator as Classifier):")
print(classification_report(y_true_binary, y_pred_classes))
print(f"Accuracy: {accuracy_score(y_true_binary, y_pred_classes):.4f}")

print(f"Original X shape: {X.shape}")
print(f"Original y shape: {y.shape}")

"""HYBRID MODEL"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam

# Build Hybrid Model (CNN + LSTM)
hybrid_model = Sequential()
hybrid_model.add(Conv1D(64, kernel_size=3, activation='relu', input_shape=(X_train_hybrid.shape[1], X_train_hybrid.shape[2])))
hybrid_model.add(MaxPooling1D(pool_size=2))
hybrid_model.add(Conv1D(128, kernel_size=3, activation='relu'))
hybrid_model.add(MaxPooling1D(pool_size=2))
hybrid_model.add(LSTM(128, return_sequences=True))
hybrid_model.add(Dropout(0.3))
hybrid_model.add(LSTM(64, return_sequences=False))
hybrid_model.add(Dropout(0.3))
hybrid_model.add(Dense(y_one_hot.shape[1], activation='softmax'))

# Compile
optimizer = Adam(learning_rate=0.001)
hybrid_model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Train
history_hybrid = hybrid_model.fit(
    X_train_hybrid, y_train_hybrid,
    epochs=100,  # More epochs, with early stopping if needed
    batch_size=64,
    validation_data=(X_test_hybrid, y_test_hybrid)
)

# GAN Setup
class Generator(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim),
            nn.Tanh()
        )
    def forward(self, z):
        return self.model(z)

class Discriminator(nn.Module):
    def __init__(self, input_dim):
        super(Discriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )
    def forward(self, x):
        return self.model(x)

# GAN Training
def train_gan(generator, discriminator, data_loader, num_epochs=50, lr=0.0001, latent_dim=20):
    loss_fn = nn.BCELoss()
    optimizer_G = optim.Adam(generator.parameters(), lr=lr)
    optimizer_D = optim.Adam(discriminator.parameters(), lr=lr)
    for epoch in range(num_epochs):
        for real_data, in data_loader:
            batch_size = real_data.size(0)
            real_labels = torch.full((batch_size, 1), 0.9)
            fake_labels = torch.full((batch_size, 1), 0.1)
            optimizer_D.zero_grad()
            real_output = discriminator(real_data)
            loss_real = loss_fn(real_output, real_labels)
            z = torch.randn(batch_size, latent_dim)
            fake_data = generator(z)
            fake_output = discriminator(fake_data.detach())
            loss_fake = loss_fn(fake_output, fake_labels)
            loss_D = loss_real + loss_fake
            loss_D.backward()
            optimizer_D.step()
            optimizer_G.zero_grad()
            fake_output = discriminator(fake_data)
            loss_G = loss_fn(fake_output, torch.ones(batch_size, 1))
            loss_G.backward()
            optimizer_G.step()
        print(f"Epoch {epoch+1}/{num_epochs}, Loss D: {loss_D.item():.4f}, Loss G: {loss_G.item():.4f}")

# GAN DataLoader
X_train_flattened = X_train_hybrid.reshape(X_train_hybrid.shape[0], -1)
data_loader = DataLoader(TensorDataset(torch.tensor(X_train_flattened, dtype=torch.float32)), batch_size=64, shuffle=True)

# Instantiate Generator and Discriminator
generator = Generator(20, X_train_flattened.shape[1])
discriminator = Discriminator(X_train_flattened.shape[1])

# Train GAN
train_gan(generator, discriminator, data_loader)

# Evaluate Hybrid Model
y_pred_hybrid = hybrid_model.predict(X_test_hybrid)
y_pred_classes_hybrid = np.argmax(y_pred_hybrid, axis=1)
y_test_classes_hybrid = np.argmax(y_test_hybrid, axis=1)

print("Hybrid Model Classification Report:")
print(classification_report(y_test_classes_hybrid, y_pred_classes_hybrid))
print(f"Hybrid Model Test Accuracy: {accuracy_score(y_test_classes_hybrid, y_pred_classes_hybrid):.4f}")

# Save Hybrid Model
hybrid_model.save('hybrid_nids_model.h5')

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.utils import to_categorical

# Prepare the data
X = data.drop('label', axis=1)
y = data['label']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_one_hot = to_categorical(y_encoded)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_reshaped = X_scaled.reshape((X_scaled.shape[0], 1, X_scaled.shape[1]))

X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y_one_hot, test_size=0.2, random_state=42)

# Build LSTM model
model = Sequential()
model.add(LSTM(units=128, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.3))
model.add(BatchNormalization())
model.add(LSTM(units=64, return_sequences=False))
model.add(Dropout(0.3))
model.add(BatchNormalization())
model.add(Dense(units=y_one_hot.shape[1], activation='softmax'))

optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

model.summary()

# Callbacks
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True, verbose=1)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.0001, verbose=1)

# Train
history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=64,
    validation_data=(X_test, y_test),
    callbacks=[early_stopping, reduce_lr]
)

# Evaluate
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

print("Classification Report:")
print(classification_report(y_test_classes, y_pred_classes))
print(f"Test Accuracy: {accuracy_score(y_test_classes, y_pred_classes):.4f}")

# Save the model
model.save('lstm_nids_model_updated.h5')

cm = confusion_matrix(y_test_classes, y_pred_classes)

# Plot it
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()